export const panel_list = [
  {
    name: 'Dashboard',
    icon: 'account_box',
    badge: false,
    badgeContent: 12,
    badgeType: '',
  },
  {
    name: 'Schedule',
    icon: 'update',
    badge: false,
    badgeContent: 1,
    badgeType: '',
  },
  {
    name: 'UI Elements',
    icon: 'photo',
    badge: false,
    badgeContent: 0,
    badgeType: '',
  },
  {
    name: 'Apps',
    icon: 'send',
    badge: false,
    badgeContent: 12,
    badgeType: '',
  },
  {
    name: 'Shared Documents',
    icon: 'perm_media',
    badge: false,
    badgeContent: 12,
    badgeType: '',
  },
  {
    name: 'Map',
    icon: 'room',
    badge: false,
    badgeContent: 0,
    badgeType: '',
  },
  {
    name: 'Team Chat',
    icon: 'forum',
    badge: false,
    badgeContent: 12,
    badgeType: '',
  },
  {
    name: 'Extras',
    icon: 'stars',
    badge: false,
    badgeContent: 12,
    badgeType: '',
  },
];
